# -*- coding: utf-8 -*-
"""Day2 (CCC).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b5pxGszRDu1KuMFf4O_zK18Yk4kGXgR7

```
Program will enter the Else written with loops 

if there is no failure in the loop (failure such as break/exception)
"""

# else (loops in general)
for i in range(3):
  if i==2:
    break
  print(i)
else:
  print("Done")

for i in range(3):
  if i==30:
    break
  print(i)
else:
  print("Done")

for i in range(3):
  if i==2:
    continue
  print(i)
else:
  print("Done")

"""Create a Python program to create the multiplication table (from 1 to 10) of a number."""

table= int(input("Table Needed:"))
for i in range(1,11):
  print(f"{table} x {i}= {table*i}")

"""```
Create a Python program to create a pattern
"""

n=int(input("No. of Rows needed:"))
for i in range(1,n+1):
  for j in range(i):
    print(i,end='')
  print()

n=int(input("No. of Rows needed:"))
for i in range(1,n+1):
  for j in range(i):
    print(j+1,end='')
  print()

n=int(input("No. of Rows needed:"))
for i in range(1,n+1):
  for j in range(i):
    print(chr(j+65),end='')
  print()
ord('C')  #for ascii value

"""```
Write a Python Program to generate Pattern
                      1
                     12
                    123
                   1234
                  12345
                 123456
               12345678
              123456789
              



"""

n=5
for i in range(1,n+1):
  for j in range(n-i):
    print(" ", end="")
  for j in range(i):
    print(j+1, end="")
  print()

"""```
Write a python program which iterates the integers from 1 to 50
for three multiples print "Fizz"
for five multiples print "Buzz"
for multiples of both 3 and 5 print "FizzBuzz"
"""

for i in range(1,51):
  if i%3==0 and i%5==0:
    print(f"{i} FizzBuzz")
  elif i%5==0:
    print(f"{i} Fizz")
  elif i%3==0:
    print(f"{i} Buzz")
  else:
    print(i)

"""```
Create a Python Program to make a hollow rhombus inside a rectangle

********************
*         *        *
*       *   *      *
*     *       *    *
*      *     *     *
*         *        *
* ******************

```
Multi-Line string

Written in '''text'''

```
String Operations
1. Concentration (+)
2. Replication (-)
"""

"Hello" + " " + "Everyone"

"Hi" + "Bruh"

print("*"*50)
print("              Hello" + "," + "Good Morning")
print("*"*50)

"""```
Write a python program that accepts an integer (n)vand computes the value of n
n = 5
Expected Result: 615 (5+55+55)
"""

n=input("Enter Value:")
int(n)+int(n*2)+int(n*3)